name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: "ghcr.io/maxik12233/"
  IMAGE_NAME: "grpc-server-image"
  PORT: "6000"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build --build-arg PORT=$PORT -t $(echo $REGISTRY)$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) ./

      - name: Run docker container
        run: docker run -e BITLY_OAUTH_TOKEN=${{secrets.BITLY_OAUTH_TOKEN}} -p $(echo $PORT):$(echo $PORT) -d $(echo $REGISTRY)$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

      - name: Unit and integration tests
        run: |
          go test ./...
        env:
          GRPC_HOST_PORT: {{$(echo $PORT)}}
          BITLY_OAUTH_TOKEN: ${{secrets.BITLY_OAUTH_TOKEN}}

      - name: Registry login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: docker push $(echo $REGISTRY)$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)


